
export let products = [
    { id: 1, name: 'Rainbow Six Seige', price: 180000,  rate : 5, tag: 'Xbox', cover: '../image/game-cover/rainbowsixCover.jpg', count: 1 ,  description: 'Tom Clancys Rainbow Six Siege is an online tactical shooter video game developed by Ubisoft Montreal and published by Ubisoft. Wikipedia' },
    { id: 2, name: 'Grand Theft Auto V', price: 150000,  rate : 5, tag: 'PC', cover: '../image/game-cover/gta5Cover.jpg', count: 1 ,  description: 'Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the seventh main entry in the Grand Theft Auto series, following 2008 Grand Theft Auto IV, and the fifteenth instalment overall. Wikipedia' },
    { id: 3, name: 'God of War 4', price: 110000,  rate : 5, tag: 'PS', cover: '../image/game-cover/godOFWar4Cover.jpg', count: 1 ,  description: 'God of War is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. It was released in April 2018 for the PlayStation 4, with a Microsoft Windows version released in January 2022. Wikipedia' },
    { id: 4, name: 'For Honor', price: 170000,  rate : 4.3, tag: 'PS', cover: '../image/game-cover/forHonorCover.jpg', count: 1 ,  description: 'This is an action game in which players control one of three factions (Samurai, Vikings, Knights) in a protracted battle for dominance. As players complete mission objectives, they use swords, axes, and spears to kill enemy warriors in melee-style combat.' },
    { id: 5, name: 'Call of duty ModerWarfare', price: 210000,  rate : 4.8, tag: 'PC', cover: '../image/game-cover/CodMWCover.jpg', count: 1 ,  description: 'Call of Duty: Modern Warfare is a 2019 first-person shooter game developed by Infinity Ward and published by Activision. Wikipedia' },
    { id: 6, name: 'Watch Dogs legion', price: 90000,  rate : 3.5, tag: 'PC', cover: '../image/game-cover/bloodlineCover.jpg', count: 1, description: 'Watch Dogs: Legion is a 2020 action-adventure game developed by Ubisoft Toronto and published by Ubisoft. It is the third instalment in the Watch Dogs series and the sequel to 2016s Watch Dogs 2. Wikipedia' },
    { id: 7, name: 'Human Fall Flat', price: 135000,  rate : 4.1, tag: 'PS', cover: '../image/game-cover/HFFCover.jpg', count: 1 ,  description: 'Human: Fall Flat is a puzzle-platform game developed by Tomas Sakalauskas and published by Curve Digital. Wikipedia' },
    { id: 8, name: 'Fifa 2022', price: 420000,  rate : 4.3, tag: 'Xbox', cover: '../image/game-cover/fifa2022Cover.jpg', count: 1 ,  description: 'FIFA 22 is an association football simulation video game published by Electronic Arts as part of the FIFA series. It is the 28th installment in the FIFA series, and was released on 9 October 2020 for Microsoft Windows, Nintendo Switch, PlayStation 4 and Xbox One. Wikipedia' },
    { id: 9, name: 'Mortal Kombat II ', price: 90000,  rate : 4.8, tag: 'PC', cover: '../image/game-cover/MK11Cover.jpg', count: 1 ,  description: 'Mortal Kombat 11 is a 2019 fighting game developed by NetherRealm Studios and published by Warner Bros. Interactive Entertainment. Wikipedia' },
    { id: 10, name: 'CyberPunk 2077', price: 140000,  rate : 4.1, tag: 'Xbox', cover: '../image/game-cover/CP2077Cover.jpg', count: 1 ,  description: 'Cyberpunk 2077 is an action role-playing video game developed by CD Projekt Red and published by CD Projekt. The story takes place in Night City, an open world set in the Cyberpunk universe. Wikipedia' },
    { id: 11, name: 'Resident Evil Village', price: 165000,  rate : 4.6, tag: 'PS', cover: '../image/game-cover/RE8Cover.jpg', count: 1 ,  description: 'Resident Evil Village is a 2021 survival horror game developed and published by Capcom. It is the sequel to Resident Evil 7: Biohazard. Players control Ethan Winters, who searches for his kidnapped daughter in a village filled with mutant creatures. Wikipedia' },
    { id: 12, name: 'State Of Deacy', price: 85000,  rate : 3.8, tag: 'PC', cover: '../image/game-cover/SODCover.jpg', count: 1 ,  description: 'State of Decay 2 is a survival video game developed by Undead Labs and published by Xbox Game Studios. The game is a followup to State of Decay and was released for Microsoft Windows and Xbox One on May 22, 2018. Wikipedia' },
    { id: 13, name: 'Skyrim', price: 70000,  rate : 4.1, tag: 'Xbox', cover: '../image/game-cover/SKYRIMCover.jpg', count: 1 ,  description: 'The Elder Scrolls V: Skyrim is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks. Wikipedia' },
]


